name: DevSecOps OIDC Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write # Requerido para solicitar el token JWT a GitHub
  contents: read  # Requerido para leer el código fuente

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout del código
        uses: actions/checkout@v4

      - name: 2. Autenticación Zero Trust en Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 3. Escaneo Estático de Seguridad (SAST)
        run: |
          curl -s -Lo tfsec https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec
          ./tfsec .

      - name: 4. Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 5. Terraform Init & Plan
        run: |
          terraform init
          terraform plan 
      - name: 6. Desplegar Infraestructura (Apply)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
